src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SettingRepository::class)
 */
class Setting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $target_usertype;

    /**
     * @ORM\OneToMany(targetEntity=UserSetting::class, mappedBy="setting")
     */
    private $userSettings;

    public function __toString()
    {
        return $this->name;
    }
    public function __construct()
    {
        $this->userSettings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getTargetUsertype(): ?string
    {
        return $this->target_usertype;
    }

    public function setTargetUsertype(string $target_usertype): self
    {
        $this->target_usertype = $target_usertype;

        return $this;
    }

    /**
     * @return Collection|UserSetting[]
     */
    public function getUserSettings(): Collection
    {
        return $this->userSettings;
    }

    public function addUserSetting(UserSetting $userSetting): self
    {
        if (!$this->userSettings->contains($userSetting)) {
            $this->userSettings[] = $userSetting;
            $userSetting->setSetting($this);
        }

        return $this;
    }

    public function removeUserSetting(UserSetting $userSetting): self
    {
        if ($this->userSettings->removeElement($userSetting)) {
            // set the owning side to null (unless already changed)
            if ($userSetting->getSetting() === $this) {
                $userSetting->setSetting(null);
            }
        }

        return $this;
    }
}

src/Form/SettingType.php
<?php

namespace App\Form;

use App\Entity\Setting;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SettingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('name')
            ->add('category')
            ->add('target_usertype')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Setting::class,
        ]);
    }
}

src/Controller/SettingController.php
<?php

namespace App\Controller;

use App\Entity\Setting;
use App\Form\SettingType;
use App\Repository\SettingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/setting")
 */
class SettingController extends AbstractController
{
    /**
     * @Route("/", name="setting_index", methods={"GET"})
     */
    public function index(SettingRepository $settingRepository): Response
    {
        return $this->render('setting/index.html.twig', [
            'settings' => $settingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="setting_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $setting = new Setting();
        $form = $this->createForm(SettingType::class, $setting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($setting);
            $entityManager->flush();

            return $this->redirectToRoute('setting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('setting/new.html.twig', [
            'setting' => $setting,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="setting_show", methods={"GET"})
     */
    public function show(Setting $setting): Response
    {
        return $this->render('setting/show.html.twig', [
            'setting' => $setting,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="setting_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Setting $setting): Response
    {
        $form = $this->createForm(SettingType::class, $setting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('setting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('setting/edit.html.twig', [
            'setting' => $setting,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="setting_delete", methods={"POST"})
     */
    public function delete(Request $request, Setting $setting): Response
    {
        if ($this->isCsrfTokenValid('delete'.$setting->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($setting);
            $entityManager->flush();
        }

        return $this->redirectToRoute('setting_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/setting/_delete_form.html.twig
<form method="post" class="float-left" action="{{ path('setting_delete', {'id': setting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ setting.id) }}">
    <button class="btn">Delete</button>
</form>

templates/setting/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/setting/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Setting{% endblock %}

{% block body %}
    <h1>Edit Setting</h1>

    {{ include('setting/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('setting_index') }}">back to list</a>

    {{ include('setting/_delete_form.html.twig') }}
{% endblock %}

templates/setting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Setting index{% endblock %}

{% block body %}
    <h1>Setting index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Name</th>
                <th>Category</th>
                <th>Target_usertype</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for setting in settings %}
            <tr>
                <td>{{ setting.id }}</td>
                <td>{{ setting.description }}</td>
                <td>{{ setting.name }}</td>
                <td>{{ setting.category }}</td>
                <td>{{ setting.targetUsertype }}</td>
                <td>
                    <a href="{{ path('setting_show', {'id': setting.id}) }}">show</a>
                    <a href="{{ path('setting_edit', {'id': setting.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('setting_new') }}">Create new</a>
{% endblock %}

templates/setting/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Setting{% endblock %}

{% block body %}
    <h1>Create new Setting</h1>

    {{ include('setting/_form.html.twig') }}

    <a href="{{ path('setting_index') }}">back to list</a>
{% endblock %}

templates/setting/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Setting{% endblock %}

{% block body %}
    <h1>Setting</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ setting.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ setting.description }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ setting.name }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ setting.category }}</td>
            </tr>
            <tr>
                <th>Target_usertype</th>
                <td>{{ setting.targetUsertype }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('setting_index') }}">back to list</a>

    <a href="{{ path('setting_edit', {'id': setting.id}) }}">edit</a>

    {{ include('setting/_delete_form.html.twig') }}
{% endblock %}